services:
  api-service:
    build: ./api-service
    container_name: api_service
    ports:
      - "8000:80"
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    container_name: user_service
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
