services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user_service
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_db
    depends_on:
      - db

  api-service:
    build:
      context: .
      dockerfile: api-service/Dockerfile
    container_name: api_service
    ports:
      - "8000:80"
    depends_on:
      - user-service

  post-service:
    build:
      context: .
      dockerfile: post-service/Dockerfile
    container_name: post_service
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db_post:5432/post_service_db
    depends_on:
      - db_post 

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_post:
    image: postgres:13
    container_name: postgres_db_post
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_service_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_post:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_post:
