# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\"\x19\n\x06PostId\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"\x19\n\x06UserId\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"?\n\rCountResponse\x12\r\n\x05views\x18\x01 \x01(\x03\x12\r\n\x05likes\x18\x02 \x01(\x03\x12\x10\n\x08\x63omments\x18\x03 \x01(\x03\")\n\nTrendPoint\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"\x1f\n\x0cTrendRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"0\n\rTrendResponse\x12\x1f\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x11.stats.TrendPoint\"+\n\nTopRequest\x12\x1d\n\x06metric\x18\x01 \x01(\x0e\x32\r.stats.Metric\")\n\x07TopPost\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\")\n\x07TopUser\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"1\n\x10TopPostsResponse\x12\x1d\n\x05posts\x18\x01 \x03(\x0b\x32\x0e.stats.TopPost\"1\n\x10TopUsersResponse\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.stats.TopUser*,\n\x06Metric\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x12\x0c\n\x08\x43OMMENTS\x10\x02\x32\xfd\x02\n\x0cStatsService\x12\x34\n\rGetPostCounts\x12\r.stats.PostId\x1a\x14.stats.CountResponse\x12>\n\x11GetPostViewsTrend\x12\x13.stats.TrendRequest\x1a\x14.stats.TrendResponse\x12>\n\x11GetPostLikesTrend\x12\x13.stats.TrendRequest\x1a\x14.stats.TrendResponse\x12\x41\n\x14GetPostCommentsTrend\x12\x13.stats.TrendRequest\x1a\x14.stats.TrendResponse\x12\x39\n\x0bGetTopPosts\x12\x11.stats.TopRequest\x1a\x17.stats.TopPostsResponse\x12\x39\n\x0bGetTopUsers\x12\x11.stats.TopRequest\x1a\x17.stats.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRIC']._serialized_start=500
  _globals['_METRIC']._serialized_end=544
  _globals['_POSTID']._serialized_start=22
  _globals['_POSTID']._serialized_end=47
  _globals['_USERID']._serialized_start=49
  _globals['_USERID']._serialized_end=74
  _globals['_COUNTRESPONSE']._serialized_start=76
  _globals['_COUNTRESPONSE']._serialized_end=139
  _globals['_TRENDPOINT']._serialized_start=141
  _globals['_TRENDPOINT']._serialized_end=182
  _globals['_TRENDREQUEST']._serialized_start=184
  _globals['_TRENDREQUEST']._serialized_end=215
  _globals['_TRENDRESPONSE']._serialized_start=217
  _globals['_TRENDRESPONSE']._serialized_end=265
  _globals['_TOPREQUEST']._serialized_start=267
  _globals['_TOPREQUEST']._serialized_end=310
  _globals['_TOPPOST']._serialized_start=312
  _globals['_TOPPOST']._serialized_end=353
  _globals['_TOPUSER']._serialized_start=355
  _globals['_TOPUSER']._serialized_end=396
  _globals['_TOPPOSTSRESPONSE']._serialized_start=398
  _globals['_TOPPOSTSRESPONSE']._serialized_end=447
  _globals['_TOPUSERSRESPONSE']._serialized_start=449
  _globals['_TOPUSERSRESPONSE']._serialized_end=498
  _globals['_STATSSERVICE']._serialized_start=547
  _globals['_STATSSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
